tension:
  decayPerSecond: 0.8
  hit: 6
  death: 35
  lowFood: 3
  darkness: 2
  nearMobFactor: 0.5
  nearMobRadius: 12

thresholds:
  calm: 20
  normal: 50
  high: 80

events:
  ambush:
    weight:
      calm: 1
      normal: 5
      high: 12
    cooldownSeconds: 240
    count: 4
    radius: 8
    mobSet: ["ZOMBIE", "SKELETON"]

  relief_drop:
    weight:
      calm: 8
      normal: 3
      high: 1
    cooldownSeconds: 600
    radius: 6
    removeAfterSeconds: 180
    # Loot entries are evaluated independently. Each can include an optional chance:
    # - Use '@0.15' for 15%% or '@15%%' for percent notation.
    # - Examples: "DIAMOND:1-3@0.15", "GOLD_INGOT:2-8@25%%", "BREAD:6-12"
    lootPool:
      # Common supplies
      - "BREAD:6-12@85%"
      - "TORCH:16-32@80%"
      - "COOKED_BEEF:6-12@65%"
      - "ARROW:16-32@60%"
      - "IRON_INGOT:4-12@70%"
      - "GOLD_INGOT:2-8@50%"
      # Uncommon
      - "EMERALD:1-3@30%"
      - "ENDER_PEARL:1-3@25%"
      - "LAPIS_LAZULI:8-16@35%"
      # Rare
      - "DIAMOND:1-3@15%"
      - "GOLDEN_CARROT:6-12@20%"
      - "OBSIDIAN:4-8@20%"
      # Very rare / jackpot
      - "ENCHANTED_GOLDEN_APPLE:1@3%"
      - "NETHERITE_INGOT:1@2%"

weather_cell:
    weight:
      calm: 0
      normal: 2
      high: 6
    cooldownSeconds: 360
    durationSeconds: 45

global:
  taggedMobKey: "director"
  bossbar:
    enabled: true
    title: "&bTension: &f%val%"