name: SMPDirector
main: dev.yourserver.smpdirector.SMPDirectorPlugin
version: ${project.version}
api-version: '1.20'
authors: [ "ChatGPT" ]
description: Dynamic AI-like event director for SMP servers.
softdepend: [PlaceholderAPI]

commands:
  director:
    description: Control the SMP Director.
    usage: /<command> <start|stop|pause|status|debug|trigger|list|reload>
    permission: director.admin

permissions:
  director.admin:
    default: op
  director.debug:
    default: op
  director.trigger:
    default: op
